# Generated by Django 4.0.4 on 2022-04-28 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saler', '0019_remove_wholesaleproductorders_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mycart',
            name='user',
        ),
        migrations.DeleteModel(
            name='SellerSlider',
        ),
        migrations.DeleteModel(
            name='MyCart',
        ),
    ]
