# Generated by Django 4.0.4 on 2022-04-28 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saler', '0021_mycart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='dow',
        ),
    ]
