# Generated by Django 4.0.4 on 2022-04-28 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saler', '0022_delete_dow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsize',
            name='size',
            field=models.CharField(max_length=30),
        ),
    ]
