# Generated by Django 4.0.4 on 2022-04-28 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saler', '0023_alter_productsize_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price_not',
        ),
    ]
