# Generated by Django 4.0.4 on 2022-05-03 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_userdetail_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='email',
        ),
    ]
